/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author MINDLUNNY
 */
public class frm_Overview_Student extends javax.swing.JFrame {

    /**
     * Creates new form frm_Ver_Detalle_Alumno
     */
    public frm_Overview_Student() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_list_students = new javax.swing.JTextArea();
        line_left = new javax.swing.JPanel();
        line_bottom = new javax.swing.JPanel();
        line_right = new javax.swing.JPanel();
        bloq_top = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea_list_students.setColumns(20);
        jTextArea_list_students.setRows(5);
        jScrollPane1.setViewportView(jTextArea_list_students);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 77, 357, 241));
        getContentPane().add(line_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 350));
        getContentPane().add(line_bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 410, 10));
        getContentPane().add(line_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 10, 350));

        bloq_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setText("EXIT");
        bloq_top.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 60, 30));

        getContentPane().add(bloq_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Overview_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Overview_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Overview_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Overview_Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Overview_Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bloq_top;
    public javax.swing.JButton btn_exit;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea_list_students;
    public javax.swing.JPanel line_bottom;
    public javax.swing.JPanel line_left;
    public javax.swing.JPanel line_right;
    // End of variables declaration//GEN-END:variables
}
