/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author MINDLUNNY
 */
public class frm_Overview_Professor extends javax.swing.JFrame {

    /**
     * Creates new form frm_Ver_Detalle_Docente
     */
    public frm_Overview_Professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_list_professors = new javax.swing.JTextArea();
        line_left = new javax.swing.JPanel();
        line_bottom = new javax.swing.JPanel();
        line_right = new javax.swing.JPanel();
        bloq_top = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea_list_professors.setColumns(20);
        jTextArea_list_professors.setRows(5);
        jScrollPane1.setViewportView(jTextArea_list_professors);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 72, 380, 240));

        javax.swing.GroupLayout line_leftLayout = new javax.swing.GroupLayout(line_left);
        line_left.setLayout(line_leftLayout);
        line_leftLayout.setHorizontalGroup(
            line_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        line_leftLayout.setVerticalGroup(
            line_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(line_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 340));

        javax.swing.GroupLayout line_bottomLayout = new javax.swing.GroupLayout(line_bottom);
        line_bottom.setLayout(line_bottomLayout);
        line_bottomLayout.setHorizontalGroup(
            line_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        line_bottomLayout.setVerticalGroup(
            line_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(line_bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 430, 10));

        javax.swing.GroupLayout line_rightLayout = new javax.swing.GroupLayout(line_right);
        line_right.setLayout(line_rightLayout);
        line_rightLayout.setHorizontalGroup(
            line_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        line_rightLayout.setVerticalGroup(
            line_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        getContentPane().add(line_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 10, 340));

        bloq_top.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_exit.setText("EXIT");
        bloq_top.add(btn_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 60, 30));

        getContentPane().add(bloq_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Overview_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Overview_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Overview_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Overview_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Overview_Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel bloq_top;
    public javax.swing.JButton btn_exit;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea_list_professors;
    public javax.swing.JPanel line_bottom;
    public javax.swing.JPanel line_left;
    public javax.swing.JPanel line_right;
    // End of variables declaration//GEN-END:variables
}
