/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author MINDLUNNY
 */
public class frm_Course extends javax.swing.JFrame {

    /**
     * Creates new form frm_Curso
     */
    public frm_Course() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_course = new javax.swing.JTable();
        btn_come_back = new javax.swing.JButton();
        txt_cod_course = new javax.swing.JTextField();
        cmbx_course_name = new javax.swing.JComboBox<>();
        jLabel_course_name = new javax.swing.JLabel();
        txt_docente = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        btn_eliminate = new javax.swing.JButton();
        btn_modify = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        line_left = new javax.swing.JPanel();
        line_bottom = new javax.swing.JPanel();
        line_right = new javax.swing.JPanel();
        line_top = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu_see_details = new javax.swing.JMenu();
        jMenuItem_professor = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_title.setText("COURSE / TEACHER");
        getContentPane().add(jLabel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jTable_course.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable_course);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 280, 661, 145));
        getContentPane().add(btn_come_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 40, 40));
        getContentPane().add(txt_cod_course, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 62, 30));

        cmbx_course_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbx_course_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 150, 30));

        jLabel_course_name.setText("COURSE NAME:");
        getContentPane().add(jLabel_course_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));
        getContentPane().add(txt_docente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 150, 30));

        btn_register.setText("REGISTER");
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 100, 30));

        btn_eliminate.setText("ELIMINATE");
        getContentPane().add(btn_eliminate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, 100, 30));

        btn_modify.setText("MODIFY");
        getContentPane().add(btn_modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 100, 30));

        btn_search.setText("SEARCH");
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, 100, 30));

        javax.swing.GroupLayout line_leftLayout = new javax.swing.GroupLayout(line_left);
        line_left.setLayout(line_leftLayout);
        line_leftLayout.setHorizontalGroup(
            line_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        line_leftLayout.setVerticalGroup(
            line_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(line_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 470));

        javax.swing.GroupLayout line_bottomLayout = new javax.swing.GroupLayout(line_bottom);
        line_bottom.setLayout(line_bottomLayout);
        line_bottomLayout.setHorizontalGroup(
            line_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        line_bottomLayout.setVerticalGroup(
            line_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(line_bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 740, 10));

        javax.swing.GroupLayout line_rightLayout = new javax.swing.GroupLayout(line_right);
        line_right.setLayout(line_rightLayout);
        line_rightLayout.setHorizontalGroup(
            line_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        line_rightLayout.setVerticalGroup(
            line_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        getContentPane().add(line_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 0, 10, 470));

        javax.swing.GroupLayout line_topLayout = new javax.swing.GroupLayout(line_top);
        line_top.setLayout(line_topLayout);
        line_topLayout.setHorizontalGroup(
            line_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 740, Short.MAX_VALUE)
        );
        line_topLayout.setVerticalGroup(
            line_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(line_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 10));

        jMenu_see_details.setText("Details");

        jMenuItem_professor.setText("Professor");
        jMenu_see_details.add(jMenuItem_professor);

        jMenuBar.add(jMenu_see_details);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Course.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Course().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_come_back;
    public javax.swing.JButton btn_eliminate;
    public javax.swing.JButton btn_modify;
    public javax.swing.JButton btn_register;
    public javax.swing.JButton btn_search;
    public javax.swing.JComboBox<String> cmbx_course_name;
    public javax.swing.JLabel jLabel_course_name;
    public javax.swing.JLabel jLabel_title;
    public javax.swing.JMenuBar jMenuBar;
    public javax.swing.JMenuItem jMenuItem_professor;
    public javax.swing.JMenu jMenu_see_details;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable_course;
    public javax.swing.JPanel line_bottom;
    public javax.swing.JPanel line_left;
    public javax.swing.JPanel line_right;
    public javax.swing.JPanel line_top;
    public javax.swing.JTextField txt_cod_course;
    public javax.swing.JTextField txt_docente;
    // End of variables declaration//GEN-END:variables
}
