/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author MINDLUNNY
 */
public class frm_Professor extends javax.swing.JFrame {

    /**
     * Creates new form frm_Docente
     */
    public frm_Professor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btn_Group_Activo = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_professor = new javax.swing.JTable();
        btn_come_back = new javax.swing.JButton();
        txt_DNI = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        jFormatted_birthday = new com.toedter.calendar.JDateChooser();
        txt_email = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        txt_cel = new javax.swing.JTextField();
        jLabel_active = new javax.swing.JLabel();
        rb_yes = new javax.swing.JRadioButton();
        rb_no = new javax.swing.JRadioButton();
        btn_register = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        btn_modify = new javax.swing.JButton();
        line_left = new javax.swing.JPanel();
        line_top = new javax.swing.JPanel();
        line_right = new javax.swing.JPanel();
        line_bottom = new javax.swing.JPanel();
        jLabel_title = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable_professor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable_professor);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 788, 140));
        getContentPane().add(btn_come_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 30, 40, 40));
        getContentPane().add(txt_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, 30));
        getContentPane().add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 150, 30));

        jFormatted_birthday.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jFormatted_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 150, 30));
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 150, 30));
        getContentPane().add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 150, 30));
        getContentPane().add(txt_cel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 100, 30));

        jLabel_active.setText("ACTIVE");
        getContentPane().add(jLabel_active, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        rb_yes.setText("Yes");
        getContentPane().add(rb_yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 210, 50, 30));

        rb_no.setText("No");
        getContentPane().add(rb_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 50, 30));

        btn_register.setText("REGISTER");
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 100, 30));

        btn_search.setText("SEARCH");
        getContentPane().add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 160, 100, 30));

        btn_modify.setText("MODIFY");
        getContentPane().add(btn_modify, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 210, 100, 30));

        javax.swing.GroupLayout line_leftLayout = new javax.swing.GroupLayout(line_left);
        line_left.setLayout(line_leftLayout);
        line_leftLayout.setHorizontalGroup(
            line_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        line_leftLayout.setVerticalGroup(
            line_leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(line_left, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 480));

        javax.swing.GroupLayout line_topLayout = new javax.swing.GroupLayout(line_top);
        line_top.setLayout(line_topLayout);
        line_topLayout.setHorizontalGroup(
            line_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        line_topLayout.setVerticalGroup(
            line_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(line_top, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 30));

        javax.swing.GroupLayout line_rightLayout = new javax.swing.GroupLayout(line_right);
        line_right.setLayout(line_rightLayout);
        line_rightLayout.setHorizontalGroup(
            line_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        line_rightLayout.setVerticalGroup(
            line_rightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(line_right, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 0, 10, 480));

        javax.swing.GroupLayout line_bottomLayout = new javax.swing.GroupLayout(line_bottom);
        line_bottom.setLayout(line_bottomLayout);
        line_bottomLayout.setHorizontalGroup(
            line_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        line_bottomLayout.setVerticalGroup(
            line_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(line_bottom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 840, 10));

        jLabel_title.setText("REGISTRATION PROFESSOR DATA");
        getContentPane().add(jLabel_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_Professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.ButtonGroup btn_Group_Activo;
    public javax.swing.JButton btn_come_back;
    public javax.swing.JButton btn_modify;
    public javax.swing.JButton btn_register;
    public javax.swing.JButton btn_search;
    public com.toedter.calendar.JDateChooser jFormatted_birthday;
    public javax.swing.JLabel jLabel_active;
    public javax.swing.JLabel jLabel_title;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    public javax.swing.JTable jTable_professor;
    public javax.swing.JPanel line_bottom;
    public javax.swing.JPanel line_left;
    public javax.swing.JPanel line_right;
    public javax.swing.JPanel line_top;
    public javax.swing.JRadioButton rb_no;
    public javax.swing.JRadioButton rb_yes;
    public javax.swing.JTextField txt_DNI;
    public javax.swing.JTextField txt_cel;
    public javax.swing.JTextField txt_email;
    public javax.swing.JTextField txt_lastname;
    public javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables

}
